--f_number VARCHAR(256) PRIMARY KEY,
--duration VARCHAR(256),
--destination VARCHAR(10) REFERENCES airport(designator),
--origin VARCHAR(10) REFERENCES airport(designator),
--seat_capacity INT CHECK(seat_capacity > 0)

INSERT INTO flight VALUES('SB123', 'AAH' , 'AAR' , 100);
INSERT INTO flight VALUES('SB124', 'AAR' , 'AAH' , 100);
INSERT INTO flight VALUES('SB255', 'YXX' , 'AAH' , 160);
INSERT INTO flight VALUES('SB256', 'AAH' , 'YXX' , 160);
INSERT INTO flight VALUES('SB377', 'AAL' , 'AES' , 220);
INSERT INTO flight VALUES('SB378', 'AES' , 'AAL' , 220);
INSERT INTO flight VALUES('SB379', 'AAW' , 'ABD' , 160);
INSERT INTO flight VALUES('SB380', 'ABD' , 'AAW' , 160);
INSERT INTO flight VALUES('SB521', 'ABD' , 'ABZ' , 100);
INSERT INTO flight VALUES('SB522', 'ABZ' , 'ABD' , 100);
INSERT INTO flight VALUES('SB879', 'ABD' , 'APG' , 160);
INSERT INTO flight VALUES('SB880', 'APG' , 'ABD' , 160);
INSERT INTO flight VALUES('SB763', 'ABG' , 'VJI' , 220);
INSERT INTO flight VALUES('SB764', 'VJI' , 'ABG' , 220);
INSERT INTO flight VALUES('SB333', 'OGO' , 'VJI' , 160);
INSERT INTO flight VALUES('SB334', 'VJI' , 'OGO' , 160);
INSERT INTO flight VALUES('SB101', 'VJI' , 'AJS' , 100);
INSERT INTO flight VALUES('SB102', 'AJS' , 'VJI' , 100);
INSERT INTO flight VALUES('SB445', 'VJI' , 'APG' , 50);
INSERT INTO flight VALUES('SB446', 'APG' , 'VJI' , 50);
INSERT INTO flight VALUES('SB43', 'VJI' , 'ADG' , 50);
INSERT INTO flight VALUES('SB44', 'ADG' , 'VJI' , 50);
INSERT INTO flight VALUES('SB221', 'ADG' , 'AXT' , 220);
INSERT INTO flight VALUES('SB222', 'AXT' , 'ADG' , 220);
INSERT INTO flight VALUES('SB677', 'ADG' , 'AFO' , 50);
INSERT INTO flight VALUES('SB678', 'AFO' , 'ADG' , 50);
INSERT INTO flight VALUES('SB55', 'AXT' , 'AAH' , 160);
INSERT INTO flight VALUES('SB56', 'AAH' , 'AXT' , 160);
INSERT INTO flight VALUES('SB831', 'AXT' , 'ABG' , 160);
INSERT INTO flight VALUES('SB832', 'ABG' , 'AXT' , 160);
INSERT INTO flight VALUES('SB591', 'AXT' , 'ZMH' , 220);
INSERT INTO flight VALUES('SB592', 'ZMH' , 'AXT' , 220);
INSERT INTO flight VALUES('SB305', 'AXT' , 'AUE' , 100);
INSERT INTO flight VALUES('SB306', 'AUE' , 'AXT' , 100);